#!/bin/bash



deps="
    bash-completion
    bc
    bzip2
    cracklib-dicts
    curl
    diffutils
    dnf-plugins-core
    findutils
    glibc-all-langpacks
    glibc-common
    glibc-locale-source
    gnupg2
    gnupg2-smime
    hostname
    iproute
    iputils
    keyutils
    krb5-libs
    less
    lsof
    man-db
    man-pages
    mtr
    ncurses
    nss-mdns
    openssh-clients
    pam
    passwd
    pigz
    pinentry
    procps-ng
    rsync
    shadow-utils
    sudo
    tcpdump
    time
    traceroute
    tree
    tzdata
    unzip
    util-linux
    vte-profile
    wget
    which
    whois
    words
    xorg-x11-xauth
    xz
    zip
    mesa-dri-drivers
    mesa-vulkan-drivers
    vulkan
"

isntalled = $('dnf repoquery --userinstalled --qf "%{name}"')

c=( $(printf "%s\n" "${a[@]}" "${b[@]}" | sort | uniq -u) )

echo c

