name="personal"
description="Personal profile"

[modules]
enabled=[
    "010-host-docker",
    "110-nvm",
    "111-chrome.install"
]

[packages]
copr=[
    "atim/lazygit",
    "atim/lazydocker"
]
install=[
    "wl-clipboard",
    "gedit",

    "git",
    "git-lfs",
    "git-email",
    "gh",

    "lazydocker",
    "lazygit"
]