name: Build GLaDOS bootc image with GHA
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 0,2,4,6"

jobs:
  build:
    name: Build Fedora bootc image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_major_version: [42,43]
        nvidia_enabled: [false]
    env:
      IMAGE_NAME: glados-bootc-image
      REGISTRY: quay.io/dpeter99
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Generate build date tag
        id: build-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set NVIDIA label suffix
        id: nvidia-label
        run: |
          if [ "${{ matrix.nvidia_enabled }}" = "true" ]; then
            echo "label=-nvidia" >> $GITHUB_OUTPUT
          else
            echo "label=" >> $GITHUB_OUTPUT
          fi

      - name: Build the immage
        id: build-image
        run: |
          podman build \
          --build-arg NVIDIA_ENABLED=${{ matrix.nvidia_enabled }} \
          --build-arg FEDORA_MAJOR_VERSION=${{ matrix.fedora_major_version }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ github.sha }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ steps.build-date.outputs.date }} \
          .


      # - name: Use buildah to create the image
      #   id: build-image
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: ${{ env.IMAGE_NAME }}
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ github.sha }}
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ steps.build-date.outputs.date }}
      #     build-args: |
      #       NVIDIA_ENABLED=${{ matrix.nvidia_enabled }}
      #       FEDORA_MAJOR_VERSION=${{ matrix.fedora_major_version }}
      #     containerfiles: |
      #       ./Containerfile

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:fedora${{ matrix.fedora_major_version }}${{ steps.nvidia-label.outputs.label }}-${{ steps.build-date.outputs.date }}


